### ISSUE TITLE
Slow speeds

### ISSUE THREAD

**Issue by hobgoblina** [sdelrio/rpi-torrent-box#10]
Any idea for testing what could be causing slow speeds through this rtorrent? I'm on gb/s fiber and I'm maxing out at 8-9mb/s while my laptop can do well above that. Seems that a lot of CPU is being used, as other services like pihole will take a while to load when downloading multiple torrents and maxing out at that 8-9mb/s speed.

**Comment by sdelrio** [comment]
Usually raspberry pi 2 with his 100mbps card through the usb controler can’t give you more. Also depends on your sd card or your usb hard drive.

**Comment by hobgoblina** [comment]
rpi4, writing to usb 3 ssd... not sure what it is :\

**Comment by sdelrio** [comment]
Don’t have a pi4 but try to create this test.tmp in your ssd and see speed 
```
sync; dd if=/dev/zero of=test.tmp bs=500K count=1024
```

**Comment by sdelrio** [comment]
5-6MB/s is normal with a pi2.

**Comment by hobgoblina** [comment]
So I *was* having slow speed over usb3 with the drive I was using, as it was running on power over USB and not getting enough from the rpi.

I've since gotten a larger drive with its own power supply. Read/write tests via dd are consistently >170mb/s, but torrent speeds are still maxing out at ~8-9mb/s.  I'm also getting slow speeds over samba, and hash-checking take pretty long... not sure if related. 

I'm capable of pulling >300mb/s over my wifi, and the ssd is writing at >170mb/s, so the bottleneck *should* be the peers available for torrents, which I'm certain isn't a consistent 8-9mb/s.

Any thoughts? I've seen some rtorrent containers that warned about rtorrent using 100% of the cpu without certain settings. I'm curious if that's the problem, as downloads always max at the same 8-9mb/s and other services (sonarr, pihole, plex, etc.) will load slowly while downloading.

**Comment by sdelrio** [comment]
The base config I did was for a pi2, I think it was like 32 max connections limit memory to 500 or 700mb etc... it should not be using 100% cpu. If you have more things, for sure it will spend your resources.
