### ISSUE TITLE
"rtorrent" user cannot access /rtorrent directory

### ISSUE THREAD

**Issue by cafca** [sdelrio/rpi-torrent-box#12]
I setup rpi-torrent-box as per the instructions, however the web ui reported that it could not connect to rtorrent. 

I investigated the error and found out that the /rtorrent directory was owned by root. After executing `chown rtorrent: /rtorrent` and restarting the container the web ui was able to connect to rtorrent as expected.

 I am not sure how to solve this issue but thought you should know.

**Comment by sdelrio** [comment]
mm strange, because use with onwer root and rtorrent is started by root user (even it should not for security)

```
$ ls -lad /mnt/
drwxr-xr-x 10 root root 184 dic 23 15:44 /mnt/
```

I think just the config of rtorrent needs it, The webserver is started with uid www-data (id=33)

Perhaps this could help you
https://github.com/sdelrio/rpi-torrent-box/issues/11

**Comment by sdelrio** [comment]
If a user needs to write probably the webserver, and that one is `www-data`, not `rtorrent`, it will probably use this folders under `/rtorrent`.

```
drwxr-xr-x 2 www-data www-data  20480 May 12 17:15 .session
drwxr-xr-x 7 www-data www-data     75 Dec 28 13:59 downloads
drwxr-xr-x 2 www-data www-data      6 Mar 13  2017 watch
```

**Comment by cafca** [comment]
I looked into `tail /var/log/php5-fpm.log`, only found some errors 

```
WARNING: [pool www] server reached pm.max_children setting (5), consider raising it
```

rtorrent being run as root is not a good idea, yes. Is there a reason why that is? Or just because you didn't get around to setting it up?

**Comment by cafca** [comment]
I mostly opened this issue so people with the same problem can find my solution. You can close this if you want to.

**Comment by sdelrio** [comment]
> I looked into `tail /var/log/php5-fpm.log`, only found some errors
> 
> ```
> WARNING: [pool www] server reached pm.max_children setting (5), consider raising it
> ```
> 
> rtorrent being run as root is not a good idea, yes. Is there a reason why that is? Or just because you didn't get around to setting it up?

Mostly didn't had free time to get arount setting it up. Shouldn't be any problems since all ports > 1024

I don't remember at the moment what's was the problem I had. Perhaps that you don't know the user used on mount  `/rtorrent` volume, or if it will have write privileges. Perhaps you could try it and make a Pull Request.
