### ISSUE TITLE
Allow larger max upload size with php/nginx config

### ISSUE THREAD

**Issue by rpgwaiter** [sdelrio/rpi-torrent-box#13]
As it is, you can't really upload more than a couple torrents at once due to the upload size limit.

**Comment by sdelrio** [comment]
How much would you need for the limit? I never hit the default limit just uploading .torrent files
The change will have to be done in two places, php.ini and nginx.conf

**Comment by rpgwaiter** [comment]
I think the limit currently is somewhere around 1M, maybe something like 25M?
