### ISSUE TITLE
bug: supervisord not found

### ISSUE THREAD

**Issue by rpgwaiter** [sdelrio/rpi-torrent-box#18]
Deploying the latest build to my cluster, I get failed pods with the error "supervisord not found". The Dockerfile installs supervisor so I'm not sure what the deal is.

**Comment by sdelrio** [comment]
Could you copy / paste the exact error?
Could be that supervisor is telling something like php-5 not found?

**Comment by sdelrio** [comment]
Just generated an image and it finds supervisord
```
docker run --rm -ti sdelrio/rtorrent-box /bin/bash
root@4c62ed6d2c36:/# whereis supervisord
supervisord: /usr/local/bin/supervisord
```

**Comment by rpgwaiter** [comment]
Turns out I messed up some strings in the helm chart, thanks for helping me narrow it down!
