### ISSUE TITLE
Command not found: supervisord

### ISSUE THREAD

**Issue by gamblor999** [sdelrio/rpi-torrent-box#20]
Hi team, I am trying to run the docker file 
sdelrio/rpi-torrent-box

But when using docker ps it shows it’s as constantly rebooting with the message
“ Command not found: supervisord”

I have run Whereis supervisord  once I used the command “ docker run --rm -ti sdelrio/rpi-torrent-box /bin/bash” 
and I get nothing.

**Comment by sdelrio** [comment]
https://github.com/sdelrio/rpi-torrent-box/issues/18

**Comment by sdelrio** [comment]
```
> docker pull sdelrio/rtorrent-box:latest
latest: Pulling from sdelrio/rtorrent-box
Digest: sha256:057ca9554ac9b5921cb9983d3b269463990d39c5265d7ea064aa47f556d9cff0
Status: Image is up to date for sdelrio/rtorrent-box:latest
docker.io/sdelrio/rtorrent-box:latest

> docker run --rm -ti sdelrio/rtorrent-box /bin/bash
root@7788d73bba2b:/# whereis supervisord
supervisord: /usr/local/bin/supervisord
root@7788d73bba2b:/# exit

> docker images | egrep rtorrent-box.+latest
sdelrio/rtorrent-box               latest                  f0d3419224af        2 months ago        378MB
MB
```

**Comment by gomsss** [comment]
I got the same problem running on the latest version v1.86, but v1.85 is working. Interestingly I'm pretty sure that I had v1.86 before upgrading my raspberry pi OS, but strangely the latest version doesn't work anymore.

```docker run --rm -ti sdelrio/rpi-torrent-box:latest /bin/bash
Digest: sha256:921c78780b07f5dd1029fabbc1bded1a08dee05baac4d9f4136da03ce1ff304a
Status: Downloaded newer image for sdelrio/rpi-torrent-box:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
root@a41a45b22bb3:/# which supervisord
root@a41a45b22bb3:/# supervisord
bash: supervisord: command not found
```

Works on v1.85
```docker run --rm -ti sdelrio/rpi-torrent-box:v1.85 /bin/bash
Digest: sha256:1987951af4f5a645c04c23f9148af5f58d9d807194d51bd2b70514276811256e
Status: Downloaded newer image for sdelrio/rpi-torrent-box:v1.85
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
root@48080b4e28f6:/# which supervisord
/usr/local/bin/supervisord
```

**Comment by gamblor999** [comment]
Nice to know I wasn’t going crazy, ended up using the old version like you
found.

**Comment by gomsss** [comment]
ok, so i was curious and loaded my old raspberry pi OS from a backup. The v1.86 image id that i had is different to the one that is in the docker hub. I think there is a bug in the current v1.86.
```
docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
sdelrio/rpi-torrent-box   latest              5d1343475bb7        19 months ago       306MB
sdelrio/rpi-torrent-box   v1.86               5d1343475bb7        19 months ago       306MB
sdelrio/rpi-torrent-box   v1.20               e7e949634e73        2 years ago         535MB
```

**Comment by sdelrio** [comment]
where did you get that 1.86? is only a 6 months old image on docker hub and yours have 19 months old ,different size and different ID
```
$ docker pull sdelrio/rpi-torrent-box:v1.86
v1.86: Pulling from sdelrio/rpi-torrent-box
```

```
$ docker images |grep rpi
sdelrio/rpi-torrent-box   v1.86               9401b710c659        6 months ago        208MB
```
As you can see in the Dockerfile the supervisord is installed with apt, are you sure you didn't use a custom Dockerfile without supervisord?

**Comment by gomsss** [comment]
@sdelrio I'm aware it's different. I'm pretty sure I got the image id `5d1343475bb7` from the docker hub repo, I didn't build the image myself. Maybe it was accidentally replaced by the new image 6 months ago.

Have you tried checking if the supervisord is available on `9401b710c659`? I've re-downloaded the image multiple times and the supervisord isn't there. I even tried to run apt install and it says the supervisor package is not available.

**Comment by gomsss** [comment]
@sdelrio To add to the comment above, the **git tag v1.86** was created on 28 Jul 2019 - this is around 19 months ago which is closer to the image `5d1343475bb7` that I got 19 months ago

However, the **v1.86 image** in docker hub was created 6 months ago. I think this image was not created from v1.86 code?

**Comment by sdelrio** [comment]
It could be, because there are some repos and links not working now at the moment. I could just manual upload a v1.86.1 with the ID 9401b710c659 (6 months s ago) until I have time to fix the repos and the build.

https://hub.docker.com/r/sdelrio/rpi-torrent-box/tags?page=1&name=v1.86.1&ordering=last_updated

**Comment by gomsss** [comment]
No probs, just to clarify that the new one `9401b710c659` is the one that's not working. The old one that I had which is `5d1343475bb7` is working fine. I'm currently using that until the new one is available.

Can you please confirm that supervisord is not in the new one ID 9401b710c659?

I'll see if I can build one from the source to find out what's going on.

**Comment by gomsss** [comment]
Btw, @sdelrio to build the image, do I need to run it on a raspberry pi, or I can run it on a linux machine?

**Comment by sdelrio** [comment]
* about  x86 machine (I guess you are refering to that, since linux are both on raspberry pi and intel/amd x86_64 arch)
You really need an arm, so you can use qemu on your x86  machine (that's why the currect CI does, look the ` docker run --rm --privileged multiarch/qemu-user-static:register --reset` on `.travis.yml`). But the execution is slow. For example the CI using emulated arm build could take +1h to build. That's why is so difficult to update and fix

The base image is `balenalib/raspberry-pi2-debian:jessie`. It worked before with the raspberry pi 2. But now seems is not detecting it correctly, so probably the supervisord packages installed are from x86 instead of arm. Will have to make tests to fix.
```
$ docker run --rm -ti balenalib/raspberry-pi2-debian:jessie /bin/sh
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
Here are a few details about this Docker image (For more information please visit https://www.balena.io/docs/reference/base-images/base-images/): 
Architecture: ARM v7 
OS: Debian Jessie 
Variant: run variant 
Default variable(s): UDEV=off 
```

**Comment by sdelrio** [comment]
I think supervisord was correct. but the config was pointing to a wrong php5-fpm binary name.
Try with this image `sdelrio/rpi-torrent-box:v1.89.3`, I've manually built on a rpi 2

**Comment by sdelrio** [comment]
also fix socket file was not correct.

**Comment by gomsss** [comment]
@sdelrio I can confirm that sdelrio/rpi-torrent-box:v1.89.3 is working. Thanks for looking into this!

**Comment by sdelrio** [comment]
Ok I wil tag the source as 1.90 then

**Comment by gomsss** [comment]
Thanks @sdelrio. Maybe worth to remove v1.86 from docker hub repo as it's not reflecting the v1.86 code. Also v1.86.1 and v1.89.3 are obselete.

**Comment by sdelrio** [comment]
ok sounds good
