### ISSUE TITLE
Modify the addons

### ISSUE THREAD

**Issue by Moumou57** [sdelrio/rpi-torrent-box#24]
Hi,

I wanted to add an addon (Material Design : https://github.com/themightykitten/ruTorrent-MaterialDesign)
But I can't find the folder where it is located.

And once it is done, how can I pull the addon into the right folder ?
With Portainer I can see directly inside the container, but I'm not sure if I can do anything from there.

**Comment by sdelrio** [comment]
The rutorrent path is in /usr/share/nginx/html

you should build your own container for that, for example you could put after installing the rutorrent.

https://github.com/sdelrio/rpi-torrent-box/blob/master/rutorrent/getrutorrent.sh

or more easy, create a new container using this one as base, just if you want to put the git clone inside probably also need to instal git,

* YourcustomDockerfile1:
```
FROM sdelrio/rpi-torrent-box:v1.9

RUN cd /usr/share/nginx/html/rutorrent/plugins/theme/themes \
        git clone git://github.com/phlooo/ruTorrent-MaterialDesign.git MaterialDesign
        (etc....)
```

 or just, clone the material desipgn locally and add to the target directory
* YourcustomDockerfile2:
```
FROM sdelrio/rpi-torrent-box:v1.9

RUN mkdir /usr/share/nginx/html/rutorrent/plugins/theme/materialdesign
COPY . /usr/share/nginx/html/rutorrent/plugins/theme/materialdesign \ 

```
