### ISSUE TITLE
make all error

### ISSUE THREAD

**Issue by nicktawan** [sdelrio/rpi-torrent-box#6]
pi@raspberrypi:~/rpi-torrent-box $ sudo make all
Cleaning build dir
Initialited build dir
echo CURL_VERSION=7.39.0
CURL_VERSION=7.39.0
test ! -s ".tmp/curl.tar.gz" && curl -s -q -L http://curl.haxx.se/download/curl-7.39.0.tar.gz -o .tmp/curl.tar.gz && \
tar xzf ".tmp/curl.tar.gz" -C ./build/ || echo ".tmp/curl.tar.gz" already exists
docker run -e CURL_VERSION=7.39.0 -ti -v /build:/usr/local/src --rm "sdelrio/gccbuilder" ./compile_curl.sh
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"./compile_curl.sh\": stat ./compile_curl.sh: no such file or directory": unknown.
Makefile:35: recipe for target 'curl' failed
make: *** [curl] Error 127

How can I do

**Comment by sdelrio** [comment]
For arm try to use sdelrio/rpi-gccbuilder as builder image , since sdelrio/gccbuilder is for intel 64bits.

**Comment by sdelrio** [comment]
At the moment you get more build details on the `.travis.yml` file. I got timeouts on travis build and had to remake the way of building image.
