### ISSUE TITLE
Download dir

### ISSUE THREAD

**Issue by Neoderek** [sdelrio/rpi-torrent-box#7]
Hi! first lot of thanks for your work with this docker.

I need to change the dir for the downloads to hdd. can I change that?

**Comment by sdelrio** [comment]
Just point your `hdd` dir with -v, inside the containre will point to `/rtorrent`:

```
docker run -dt --name rpi-torrent_01 \
  -p 8080:80 -p 8443:443 -p 49160:49160/udp -p 49161:49161 
  -v /hdd:/rtorrent
  -e NEW_USER=myuser
  -e NEW_PASS=mypass
  sdelrio/rpi-torrent-box
```
