### ISSUE TITLE
Expose SCGI port?

### ISSUE THREAD

**Issue by hobgoblina** [sdelrio/rpi-torrent-box#9]
Got this all up and running, but I'm trying to see if I can get the rtorrent in this container to work with the Flood frontend in another container (https://github.com/Flood-UI/flood/wiki/Docker). I need the SCGI port to connect them. Looking at the .rtorrent.rc file, it has the rtorrent SCGI port listed as 5000. Tried building the container with that port exposed, as well as 49161 and whatnot, but no luck.

Any help would be much appreciated.

**Comment by sdelrio** [comment]
By default scgi_port only watch on localhost ([rtorrent.rc](https://github.com/sdelrio/rpi-torrent-box/blob/master/rtorrent/config/.rtorrent.rc)):
```
scgi_port=127.0.0.1:5000
```
You can change it and make it watch on `0.0.0.0:5000` or if you are working with kubernetes, then anothher container in the same pod could connect to `127.0.0.1:5000`

**Comment by hobgoblina** [comment]
I'm trying `127.0.0.1:5000`... I'm just not able to connect to rtorrent from services in other containers (sonarr isn't connecting either), even though they're  linked and in the same docker network.

Also tried using the container's IP and docker network gateway, even though it shouldn't be necessary. Nothing's working.

**Comment by hobgoblina** [comment]
Here's the run directive I used...

```
docker run -dt --net torrents --name rtorrent \
--link sonarr:sonarr \
--link flood:flood \
--expose 5000 \
-p 8000:80 -p 8443:443 -p 49160:49160/udp -p 49161:49161 -p 5000:5000 \
-v /foo:/rtorrent \
-e TZ=America/New_York \
--restart=always \
sdelrio/rpi-torrent-box
```

**Comment by hobgoblina** [comment]
Ahh, my dumbass was trying to go off of the remapped exposed port 8000 instead of the internal port 80. Thanks!

**Comment by hobgoblina** [comment]
Well, actually I connected sonarr with port 80... it was looking for the interface. Still can't connect to flood via the SCGI port 5000.

**Comment by sdelrio** [comment]
as I told, change config `scgi_port=0.0.0.0:5000`

**Comment by hobgoblina** [comment]
Ahh, my bad. I misunderstood. That did it!
